import React, { useState, useEffect, useRef, useCallback, useMemo } from "react";
import * as mammoth from "mammoth";
import JSZip from "jszip";
import { GlobalWorkerOptions, getDocument } from "pdfjs-dist";
import pdfWorkerUrl from "pdfjs-dist/build/pdf.worker.min.mjs?url";
import { supabase, BOOKS_BUCKET, ASSETS_BUCKET } from "./supabaseClient";
import {
  BookOpen, BookMarked, Library, Upload, FileText, Download, Trash2, Plus,
  ArrowLeft, X, Check, AlertCircle, Loader2, Pencil, Save, RotateCcw,
  ChevronLeft, ChevronRight, LayoutDashboard, BookCopy, Clock, CheckCircle2,
  Settings as SettingsIcon, Sparkles, Sun, Moon, ZoomIn, ZoomOut
} from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, ResponsiveContainer, Tooltip, Cell } from "recharts";

GlobalWorkerOptions.workerSrc = pdfWorkerUrl;

/* ============================== PALETTE ============================== */
// Primary/accent are themeable at runtime via CSS variables (set from Settings).
// The hex values here are just the DEFAULT values written into :root below.
const DEFAULT_PRIMARY = "#5B2A2E";
const DEFAULT_PRIMARY_DARK = "#3E1D20";
const DEFAULT_ACCENT = "#AD8A56";

const INK = "var(--ink)";
const LEATHER = "var(--leather)";
const LEATHER_DARK = "var(--leather-dark)";
const GOLD = "var(--gold)";
const PAPER = "var(--bg)";
const CARD = "var(--card)";
const MUTED = "var(--muted)";
const GREEN = "#3F7A57";
const RED = "#C24444";
const BORDER = "var(--border)";

function darkenHex(hex, factor = 0.7) {
  try {
    const h = hex.replace("#", "");
    const r = Math.round(parseInt(h.substring(0, 2), 16) * factor);
    const g = Math.round(parseInt(h.substring(2, 4), 16) * factor);
    const b = Math.round(parseInt(h.substring(4, 6), 16) * factor);
    return `#${[r, g, b].map((v) => Math.max(0, Math.min(255, v)).toString(16).padStart(2, "0")).join("")}`;
  } catch (e) { return DEFAULT_PRIMARY_DARK; }
}

const SPINES = ["#5B2A2E", "#2F4858", "#4C6444", "#7A5230", "#5C4A72"];
function spineColor(seed) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  return SPINES[h % SPINES.length];
}

/* ============================== HELPERS ============================== */
const MAX_FILE_BYTES = 15 * 1024 * 1024; // Supabase free tier allows much bigger files than artifact storage

function fmtBytes(b) {
  if (b < 1024) return b + " B";
  if (b < 1024 * 1024) return (b / 1024).toFixed(0) + " KB";
  return (b / (1024 * 1024)).toFixed(1) + " MB";
}
function fmtStamp(iso) {
  if (!iso) return { date: "—", time: "" };
  const d = new Date(iso);
  return {
    date: d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" }),
    time: d.toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" }),
  };
}
function extOf(name) {
  const m = /\.([a-zA-Z0-9]+)$/.exec(name || "");
  return m ? m[1].toLowerCase() : "";
}
function cleanBaseName(filename) {
  return filename.replace(/\.[^/.]+$/, "").replace(/[_-]+/g, " ").trim();
}
function progressOf(book) {
  const total = book.total_pages || 1;
  return Math.min(100, Math.round(((book.last_read_page || 0) / total) * 100));
}
function statusOf(book) {
  const p = progressOf(book);
  if (p <= 0) return { label: "Not started", color: MUTED };
  if (p >= 100) return { label: "Finished", color: GREEN };
  return { label: "Reading", color: GOLD };
}

/* ---- Smart page-count detection ----
   PDF: reads the real page count via PDF.js.
   DOCX: reads Word's own cached page-count metadata (docProps/app.xml),
         falling back to a word-count-based estimate (~275 words/page)
         if that metadata is missing. Legacy .doc files aren't supported
         in-browser, so detection is skipped for those. */
async function detectPdfPageCount(file) {
  const buf = await file.arrayBuffer();
  const doc = await getDocument({ data: buf }).promise;
  return doc.numPages || null;
}

async function detectDocxPageCount(file) {
  try {
    const buf = await file.arrayBuffer();
    // 1) Try Word's own cached metadata first (fast, authoritative when present)
    try {
      const zip = await JSZip.loadAsync(buf);
      const appXmlFile = zip.file("docProps/app.xml");
      if (appXmlFile) {
        const xml = await appXmlFile.async("string");
        const pagesMatch = /<Pages>(\d+)<\/Pages>/.exec(xml);
        if (pagesMatch && parseInt(pagesMatch[1], 10) > 0) return parseInt(pagesMatch[1], 10);
      }
    } catch (e) { /* fall through */ }

    // 2) Fallback: extract the ACTUAL text and estimate from a real word count.
    // This covers files with no cached metadata at all (common for documents
    // generated by tools other than Microsoft Word itself).
    const result = await mammoth.extractRawText({ arrayBuffer: buf });
    const words = (result.value || "").trim().split(/\s+/).filter(Boolean).length;
    if (words > 0) return Math.max(1, Math.round(words / 275));
  } catch (e) { /* fall through to null */ }
  return null;
}

/* ---- Split flowing docx HTML into readable chunks based on actual content
   size (NOT forced to match the declared page count — a document may not have
   enough natural break-points to hit an arbitrary target, which previously
   caused the page counter to silently fall short of the real total). The
   reader maps these chunks proportionally onto the declared total page count,
   so "Page X of Y" and progress % always stay accurate to what you set. ---- */
function chunkHtmlForReading(html) {
  const TARGET_CHARS_PER_CHUNK = 1500;
  try {
    const doc = new DOMParser().parseFromString(html || "", "text/html");
    const nodes = Array.from(doc.body.children);
    if (nodes.length === 0) return [html || ""];
    const chunks = [];
    let current = [];
    let currentLen = 0;
    nodes.forEach((node) => {
      const len = (node.textContent || "").length + (node.tagName === "TABLE" ? 400 : 0);
      current.push(node.outerHTML);
      currentLen += len;
      if (currentLen >= TARGET_CHARS_PER_CHUNK) {
        chunks.push(current.join(""));
        current = [];
        currentLen = 0;
      }
    });
    if (current.length) chunks.push(current.join(""));
    return chunks.length ? chunks : [html || ""];
  } catch (e) {
    return [html || ""];
  }
}

async function detectPageCount(file, ext) {
  try {
    if (ext === "pdf") return await detectPdfPageCount(file);
    if (ext === "docx") return await detectDocxPageCount(file);
  } catch (e) { return null; }
  return null; // legacy .doc — not supported in-browser
}

/* ============================== ROOT APP ============================== */
export default function App() {
  const [ready, setReady] = useState(false);
  const [folders, setFolders] = useState([]);
  const [booksByFolder, setBooksByFolder] = useState({});
  const [view, setView] = useState("dashboard");
  const [activeFolderId, setActiveFolderId] = useState(null);

  const [showNewFolder, setShowNewFolder] = useState(false);
  const [newFolderName, setNewFolderName] = useState("");

  const [pendingFile, setPendingFile] = useState(null);
  const [pendingName, setPendingName] = useState("");
  const [pendingPages, setPendingPages] = useState("");
  const [uploadError, setUploadError] = useState("");
  const [saving, setSaving] = useState(false);
  const fileInputRef = useRef(null);

  const [confirmDelete, setConfirmDelete] = useState(null);
  const [toast, setToast] = useState("");
  const [readingTarget, setReadingTarget] = useState(null);
  const [loadError, setLoadError] = useState("");

  const [theme, setTheme] = useState({
    site_name: "Readnexa",
    tagline: "Read · Track · Remember",
    logo_url: null,
    primary_color: DEFAULT_PRIMARY,
    accent_color: DEFAULT_ACCENT,
  });
  const [showSettings, setShowSettings] = useState(false);

  const [showEditFolder, setShowEditFolder] = useState(null); // {id, name}
  const [editFolderName, setEditFolderName] = useState("");
  const [editFolderError, setEditFolderError] = useState("");

  const [editingBook, setEditingBook] = useState(null); // {folderId, id, name, total_pages}
  const [confirmReset, setConfirmReset] = useState(null); // {folderId, id, name}

  const resetProgress = async (folderId, id) => {
    await updateBook(folderId, id, { last_read_page: 0, last_read_at: null });
    setConfirmReset(null);
    showToast("Progress reset to 0%");
  };

  const [mode, setMode] = useState(() => {
    try { return localStorage.getItem("readnexa-mode") || "light"; } catch (e) { return "light"; }
  });
  useEffect(() => {
    document.documentElement.classList.toggle("dark", mode === "dark");
    try { localStorage.setItem("readnexa-mode", mode); } catch (e) {}
  }, [mode]);
  const toggleMode = () => setMode((m) => (m === "light" ? "dark" : "light"));

  // Page-count detection state for the upload flow
  const [pageStage, setPageStage] = useState("entry"); // detecting | confirm | entry
  const [detectedPages, setDetectedPages] = useState(null);
  const [detectFailed, setDetectFailed] = useState(false);

  const showToast = (msg) => { setToast(msg); setTimeout(() => setToast(""), 2800); };

  const applyTheme = (t) => {
    document.documentElement.style.setProperty("--leather", t.primary_color || DEFAULT_PRIMARY);
    document.documentElement.style.setProperty("--leather-dark", darkenHex(t.primary_color || DEFAULT_PRIMARY, 0.68));
    document.documentElement.style.setProperty("--gold", t.accent_color || DEFAULT_ACCENT);
  };

  const loadAll = useCallback(async () => {
    setLoadError("");
    const { data: folderRows, error: fErr } = await supabase.from("folders").select("*").order("created_at");
    if (fErr) { setLoadError(fErr.message); setReady(true); return; }
    setFolders(folderRows || []);

    const { data: bookRows, error: bErr } = await supabase.from("books").select("*").order("uploaded_at", { ascending: false });
    if (bErr) { setLoadError(bErr.message); setReady(true); return; }
    const grouped = {};
    (folderRows || []).forEach((f) => (grouped[f.id] = []));
    (bookRows || []).forEach((b) => {
      if (!grouped[b.folder_id]) grouped[b.folder_id] = [];
      grouped[b.folder_id].push(b);
    });
    setBooksByFolder(grouped);

    const { data: settingsRow } = await supabase.from("site_settings").select("*").eq("id", 1).maybeSingle();
    if (settingsRow) {
      setTheme(settingsRow);
      applyTheme(settingsRow);
    } else {
      applyTheme(theme);
    }

    setReady(true);
  }, []);

  useEffect(() => { loadAll(); }, [loadAll]);

  const isDuplicateFolderName = (name, excludeId = null) =>
    folders.some((f) => f.id !== excludeId && f.name.trim().toLowerCase() === name.trim().toLowerCase());

  const saveSettings = async (patch) => {
    const next = { ...theme, ...patch };
    const { error } = await supabase.from("site_settings").upsert({ id: 1, ...next });
    if (error) { showToast("Could not save settings: " + error.message); return; }
    setTheme(next);
    applyTheme(next);
    showToast("Settings saved");
  };

  const renameFolder = async () => {
    const name = editFolderName.trim();
    if (!name) return;
    if (isDuplicateFolderName(name, showEditFolder.id)) {
      setEditFolderError("A shelf with this name already exists.");
      return;
    }
    const { error } = await supabase.from("folders").update({ name }).eq("id", showEditFolder.id);
    if (error) { setEditFolderError(error.message); return; }
    setFolders((prev) => prev.map((f) => (f.id === showEditFolder.id ? { ...f, name } : f)));
    setShowEditFolder(null); setEditFolderName(""); setEditFolderError("");
    showToast("Shelf renamed");
  };

  const saveBookEdit = async () => {
    if (!editingBook) return;
    const name = editingBook.name.trim();
    const pages = parseInt(editingBook.total_pages, 10);
    if (!name) return;
    if (!pages || pages < 1) { showToast("Total pages must be 1 or more."); return; }
    const list = booksByFolder[editingBook.folderId] || [];
    const current = list.find((b) => b.id === editingBook.id);
    const clampedLastRead = Math.min(current ? current.last_read_page || 0 : 0, pages);
    const patch = { name, total_pages: pages, last_read_page: clampedLastRead };
    const { error } = await supabase.from("books").update(patch).eq("id", editingBook.id);
    if (error) { showToast("Could not save: " + error.message); return; }
    setBooksByFolder((prev) => ({
      ...prev,
      [editingBook.folderId]: (prev[editingBook.folderId] || []).map((b) => (b.id === editingBook.id ? { ...b, ...patch } : b)),
    }));
    setEditingBook(null);
    showToast("Book updated");
  };

  const [newFolderError, setNewFolderError] = useState("");

  const createFolder = async () => {
    const name = newFolderName.trim();
    if (!name) return;
    if (isDuplicateFolderName(name)) {
      setNewFolderError("A shelf with this name already exists. Choose a different name.");
      return;
    }
    const id = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") + "-" + Date.now().toString(36);
    const { error } = await supabase.from("folders").insert({ id, name });
    if (error) { setNewFolderError("Could not create shelf: " + error.message); return; }
    setFolders((prev) => [...prev, { id, name, created_at: new Date().toISOString() }]);
    setBooksByFolder((prev) => ({ ...prev, [id]: [] }));
    setShowNewFolder(false); setNewFolderName(""); setNewFolderError("");
    showToast(`Shelf "${name}" created`);
  };

  const deleteFolder = async (id) => {
    const books = booksByFolder[id] || [];
    for (const b of books) {
      if (b.storage_path) await supabase.storage.from(BOOKS_BUCKET).remove([b.storage_path]);
    }
    await supabase.from("books").delete().eq("folder_id", id);
    await supabase.from("folders").delete().eq("id", id);
    setFolders((prev) => prev.filter((f) => f.id !== id));
    setBooksByFolder((prev) => { const c = { ...prev }; delete c[id]; return c; });
    if (activeFolderId === id) { setView("dashboard"); setActiveFolderId(null); }
    setConfirmDelete(null);
    showToast("Shelf deleted");
  };

  const openFolder = (id) => { setActiveFolderId(id); setView("shelf"); };

  const onPickFile = () => fileInputRef.current && fileInputRef.current.click();
  const onFileSelected = async (e) => {
    const file = e.target.files && e.target.files[0];
    e.target.value = "";
    if (!file) return;
    setUploadError("");
    const ext = extOf(file.name);
    if (!["pdf", "doc", "docx"].includes(ext)) { setUploadError("Only PDF and Word (.doc, .docx) files are supported."); return; }
    if (file.size > MAX_FILE_BYTES) { setUploadError(`File is too large (${fmtBytes(file.size)}). Keep files under ${fmtBytes(MAX_FILE_BYTES)}.`); return; }
    setPendingFile({ file, ext, size: file.size });
    setPendingName(cleanBaseName(file.name));
    setPendingPages("");
    setDetectedPages(null);
    setDetectFailed(false);
    setPageStage("detecting");

    const detected = await detectPageCount(file, ext);
    if (detected && detected > 0) {
      setDetectedPages(detected);
      setPendingPages(String(detected));
      setPageStage("confirm");
    } else {
      setDetectFailed(true);
      setPageStage("entry");
    }
  };
  const cancelUpload = () => {
    setPendingFile(null); setPendingName(""); setPendingPages(""); setUploadError("");
    setPageStage("entry"); setDetectedPages(null); setDetectFailed(false);
  };
  const confirmDetectedPages = (accepted) => {
    if (!accepted) setPendingPages("");
    setPageStage("entry");
  };

  const confirmUploadSave = async () => {
    const pages = parseInt(pendingPages, 10);
    if (!pendingFile || !pendingName.trim()) return;
    if (!pages || pages < 1) { setUploadError("Please enter the total number of pages (a whole number, 1 or more)."); return; }
    setSaving(true);

    const bookId = "b_" + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
    const storagePath = `${activeFolderId}/${bookId}-${pendingFile.file.name}`;

    const { error: upErr } = await supabase.storage.from(BOOKS_BUCKET).upload(storagePath, pendingFile.file, {
      cacheControl: "3600",
      upsert: false,
    });
    if (upErr) { setUploadError("Upload failed: " + upErr.message); setSaving(false); return; }

    const { data: pub } = supabase.storage.from(BOOKS_BUCKET).getPublicUrl(storagePath);
    const fileUrl = pub.publicUrl;

    const row = {
      id: bookId,
      folder_id: activeFolderId,
      name: pendingName.trim(),
      file_name: pendingFile.file.name,
      file_type: pendingFile.ext,
      size: pendingFile.size,
      total_pages: pages,
      last_read_page: 0,
      uploaded_at: new Date().toISOString(),
      last_read_at: null,
      file_url: fileUrl,
      storage_path: storagePath,
      edited_html: null,
      edited_at: null,
    };

    const { error: insErr } = await supabase.from("books").insert(row);
    if (insErr) { setUploadError("Could not save book record: " + insErr.message); setSaving(false); return; }

    setBooksByFolder((prev) => ({ ...prev, [activeFolderId]: [row, ...(prev[activeFolderId] || [])] }));
    setSaving(false); cancelUpload();
    showToast(`"${row.name}" added to shelf`);
  };

  const deleteBook = async (folderId, bookId) => {
    const book = (booksByFolder[folderId] || []).find((b) => b.id === bookId);
    if (book && book.storage_path) await supabase.storage.from(BOOKS_BUCKET).remove([book.storage_path]);
    await supabase.from("books").delete().eq("id", bookId);
    setBooksByFolder((prev) => ({ ...prev, [folderId]: (prev[folderId] || []).filter((b) => b.id !== bookId) }));
    setConfirmDelete(null);
    showToast("Book removed");
  };

  const updateBook = async (folderId, bookId, patch) => {
    const { error } = await supabase.from("books").update(patch).eq("id", bookId);
    if (error) { showToast("Could not save: " + error.message); return; }
    setBooksByFolder((prev) => ({
      ...prev,
      [folderId]: (prev[folderId] || []).map((b) => (b.id === bookId ? { ...b, ...patch } : b)),
    }));
  };

  const activeFolder = folders.find((f) => f.id === activeFolderId);
  const activeBooks = booksByFolder[activeFolderId] || [];

  const allBooksFlat = useMemo(() => {
    const out = [];
    folders.forEach((f) => (booksByFolder[f.id] || []).forEach((b) => out.push({ ...b, folderName: f.name })));
    return out;
  }, [folders, booksByFolder]);

  return (
    <div className="min-h-screen w-full" style={{ background: PAPER }}>
      <style>{`
        :root {
          --leather: ${DEFAULT_PRIMARY};
          --leather-dark: ${DEFAULT_PRIMARY_DARK};
          --gold: ${DEFAULT_ACCENT};
          --bg: #F6F1E6;
          --card: #FFFDF8;
          --ink: #241A15;
          --muted: #8A7B68;
          --border: #E4DAC7;
          --soft: #EFE7D5;
        }
        html.dark {
          --bg: #171310;
          --card: #221C18;
          --ink: #F1EAE0;
          --muted: #A79A89;
          --border: #3A322B;
          --soft: #2A241E;
        }
        html.dark body { background: var(--bg); }
        @keyframes riseIn { from { opacity:0; transform: translateY(14px); } to { opacity:1; transform: translateY(0); } }
        @keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
        @keyframes popIn { from { opacity:0; transform: scale(.94); } to { opacity:1; transform: scale(1); } }
        .rise { animation: riseIn .5s ease both; }
        .fade { animation: fadeIn .25s ease both; }
        .pop { animation: popIn .22s cubic-bezier(.2,.9,.3,1.2) both; }
        .book-card { transition: transform .28s ease, box-shadow .28s ease; }
        .book-card:hover { transform: translateY(-6px); box-shadow: 0 18px 30px -14px rgba(36,26,21,0.35); }
        .shelf-card { transition: transform .25s ease, box-shadow .25s ease; }
        .shelf-card:hover { transform: translateY(-4px); box-shadow: 0 14px 26px -12px rgba(36,26,21,0.3); }
        .btn-lift { transition: transform .15s ease, filter .15s ease; }
        .btn-lift:hover { transform: translateY(-1px); filter: brightness(1.06); }
        .progress-fill { transition: width .8s cubic-bezier(.2,.8,.3,1); }
        .editing-live[data-editable="true"] { color: ${GREEN} !important; }
        ::-webkit-scrollbar { width: 10px; height:10px; }
        ::-webkit-scrollbar-thumb { background: ${BORDER}; border-radius: 8px; }
      `}</style>

      <input ref={fileInputRef} type="file" accept=".pdf,.doc,.docx" className="hidden" onChange={onFileSelected} />

      <TopBar view={view} theme={theme} mode={mode} onToggleMode={toggleMode} onHome={() => { setView("dashboard"); setActiveFolderId(null); }} onOpenSettings={() => setShowSettings(true)} />

      <main className="max-w-6xl mx-auto px-6 py-8">
        {loadError && (
          <div className="mb-6 p-4 rounded-lg text-sm flex items-start gap-2" style={{ background: "#FBEAEA", color: RED }}>
            <AlertCircle size={16} className="mt-0.5 shrink-0" />
            <div>
              <p className="font-medium">Could not load your library from Supabase.</p>
              <p className="mt-1 font-mono text-xs">{loadError}</p>
              <p className="mt-1">Check that your Supabase URL/key are set correctly and that the `folders` and `books` tables exist.</p>
            </div>
          </div>
        )}
        {!ready ? (
          <div className="flex items-center gap-2 py-24 justify-center" style={{ color: MUTED }}>
            <Loader2 className="animate-spin" size={20} /> Opening your library…
          </div>
        ) : view === "dashboard" ? (
          <Dashboard
            folders={folders}
            booksByFolder={booksByFolder}
            allBooksFlat={allBooksFlat}
            onOpenFolder={openFolder}
            onNewFolder={() => setShowNewFolder(true)}
            onEditFolder={(f) => { setShowEditFolder(f); setEditFolderName(f.name); setEditFolderError(""); }}
            onDeleteFolder={(f) => setConfirmDelete({ type: "folder", id: f.id, name: f.name })}
            onContinueReading={(b) => setReadingTarget({ folderId: b.folder_id, book: b })}
          />
        ) : (
          <ShelfView
            folder={activeFolder}
            books={activeBooks}
            onBack={() => { setView("dashboard"); setActiveFolderId(null); }}
            onUploadClick={onPickFile}
            onRead={(book) => setReadingTarget({ folderId: activeFolderId, book })}
            onEditBook={(b) => setEditingBook({ folderId: activeFolderId, id: b.id, name: b.name, total_pages: b.total_pages })}
            onResetProgress={(b) => setConfirmReset({ folderId: activeFolderId, id: b.id, name: b.name })}
            onDeleteBook={(b) => setConfirmDelete({ type: "book", id: b.id, name: b.name, folderId: activeFolderId })}
          />
        )}
      </main>

      {showNewFolder && (
        <Modal onClose={() => { setShowNewFolder(false); setNewFolderName(""); setNewFolderError(""); }}>
          <h3 className="font-serif text-xl font-bold mb-4" style={{ color: LEATHER_DARK }}>New shelf</h3>
          <label className="text-sm block mb-1" style={{ color: MUTED }}>Shelf name</label>
          <input autoFocus value={newFolderName} onChange={(e) => { setNewFolderName(e.target.value); setNewFolderError(""); }}
            onKeyDown={(e) => e.key === "Enter" && createFolder()} placeholder="e.g. Business Analysis"
            className="w-full border rounded-md px-3 py-2 mb-2 focus:outline-none focus:ring-2"
            style={{ borderColor: newFolderError ? RED : BORDER }} />
          {newFolderError && <p className="text-sm flex items-center gap-1.5 mb-3" style={{ color: RED }}><AlertCircle size={14} /> {newFolderError}</p>}
          <div className="flex justify-end gap-3 mt-3">
            <button onClick={() => { setShowNewFolder(false); setNewFolderName(""); setNewFolderError(""); }} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>Cancel</button>
            <button onClick={createFolder} disabled={!newFolderName.trim()} className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white disabled:opacity-40" style={{ background: LEATHER }}>Create shelf</button>
          </div>
        </Modal>
      )}

      {showEditFolder && (
        <Modal onClose={() => { setShowEditFolder(null); setEditFolderError(""); }}>
          <h3 className="font-serif text-xl font-bold mb-4" style={{ color: LEATHER_DARK }}>Rename shelf</h3>
          <label className="text-sm block mb-1" style={{ color: MUTED }}>Shelf name</label>
          <input autoFocus value={editFolderName} onChange={(e) => { setEditFolderName(e.target.value); setEditFolderError(""); }}
            onKeyDown={(e) => e.key === "Enter" && renameFolder()}
            className="w-full border rounded-md px-3 py-2 mb-2 focus:outline-none focus:ring-2"
            style={{ borderColor: editFolderError ? RED : BORDER }} />
          {editFolderError && <p className="text-sm flex items-center gap-1.5 mb-3" style={{ color: RED }}><AlertCircle size={14} /> {editFolderError}</p>}
          <div className="flex justify-end gap-3 mt-3">
            <button onClick={() => { setShowEditFolder(null); setEditFolderError(""); }} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>Cancel</button>
            <button onClick={renameFolder} disabled={!editFolderName.trim()} className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white disabled:opacity-40" style={{ background: LEATHER }}>Save name</button>
          </div>
        </Modal>
      )}

      {editingBook && (
        <Modal onClose={() => setEditingBook(null)}>
          <h3 className="font-serif text-xl font-bold mb-4" style={{ color: LEATHER_DARK }}>Edit book details</h3>
          <label className="text-sm block mb-1" style={{ color: MUTED }}>Book / document name</label>
          <input autoFocus value={editingBook.name} onChange={(e) => setEditingBook({ ...editingBook, name: e.target.value })}
            className="w-full border rounded-md px-3 py-2 mb-4 focus:outline-none focus:ring-2" style={{ borderColor: BORDER }} />
          <label className="text-sm block mb-1" style={{ color: MUTED }}>Total pages</label>
          <input type="number" min="1" value={editingBook.total_pages} onChange={(e) => setEditingBook({ ...editingBook, total_pages: e.target.value })}
            onKeyDown={(e) => e.key === "Enter" && saveBookEdit()}
            className="w-full border rounded-md px-3 py-2 mb-2 focus:outline-none focus:ring-2" style={{ borderColor: BORDER }} />
          <p className="text-xs mb-3" style={{ color: MUTED }}>If you lower the page count below your current reading progress, progress will be adjusted automatically.</p>
          <div className="flex justify-end gap-3 mt-3">
            <button onClick={() => setEditingBook(null)} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>Cancel</button>
            <button onClick={saveBookEdit} disabled={!editingBook.name.trim()} className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white disabled:opacity-40" style={{ background: LEATHER }}>Save changes</button>
          </div>
        </Modal>
      )}

      {confirmReset && (
        <Modal onClose={() => setConfirmReset(null)}>
          <h3 className="font-serif text-xl font-bold mb-2" style={{ color: LEATHER_DARK }}>Reset reading progress?</h3>
          <p className="text-sm mb-6" style={{ color: MUTED }}>
            "{confirmReset.name}" will go back to <span className="font-semibold">0%</span> — its current progress will be lost. This cannot be undone.
          </p>
          <div className="flex justify-end gap-3">
            <button onClick={() => setConfirmReset(null)} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>Cancel</button>
            <button onClick={() => resetProgress(confirmReset.folderId, confirmReset.id)}
              className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white flex items-center gap-2" style={{ background: LEATHER }}>
              <RotateCcw size={14} /> Reset to 0%
            </button>
          </div>
        </Modal>
      )}

      {showSettings && (
        <SettingsModal theme={theme} onClose={() => setShowSettings(false)} onSave={saveSettings} />
      )}

      {pendingFile && (
        <Modal onClose={cancelUpload}>
          <h3 className="font-serif text-xl font-bold mb-1" style={{ color: LEATHER_DARK }}>Add this book</h3>
          <p className="text-sm mb-4" style={{ color: MUTED }}>File: <span className="font-mono">{pendingFile.file.name}</span> ({fmtBytes(pendingFile.size)})</p>
          <label className="text-sm block mb-1" style={{ color: MUTED }}>Book / document name</label>
          <input autoFocus value={pendingName} onChange={(e) => setPendingName(e.target.value)}
            className="w-full border rounded-md px-3 py-2 mb-4 focus:outline-none focus:ring-2" style={{ borderColor: BORDER }} />

          {pageStage === "detecting" && (
            <div className="flex items-center gap-2 mb-4 p-3 rounded-md" style={{ background: "var(--soft)" }}>
              <Loader2 className="animate-spin shrink-0" size={16} style={{ color: LEATHER }} />
              <p className="text-sm" style={{ color: MUTED }}>Analyzing document to detect page count…</p>
            </div>
          )}

          {pageStage === "confirm" && (
            <div className="mb-4 p-3 rounded-md" style={{ background: "var(--soft)" }}>
              <p className="text-sm flex items-center gap-1.5 mb-3" style={{ color: LEATHER_DARK }}>
                <Sparkles size={15} style={{ color: GOLD }} /> We detected <span className="font-bold">{detectedPages}</span> pages in this document. Is that correct?
              </p>
              <div className="flex gap-2">
                <button onClick={() => confirmDetectedPages(false)} className="px-3 py-1.5 rounded-md text-sm" style={{ border: `1px solid ${BORDER}`, color: LEATHER_DARK }}>No, let me correct it</button>
                <button onClick={() => confirmDetectedPages(true)} className="btn-lift px-3 py-1.5 rounded-md text-sm font-medium text-white flex items-center gap-1.5" style={{ background: GREEN }}>
                  <Check size={14} /> Yes, that's correct
                </button>
              </div>
            </div>
          )}

          {pageStage === "entry" && (
            <>
              <label className="text-sm block mb-1" style={{ color: MUTED }}>Total pages</label>
              <input type="number" min="1" value={pendingPages} onChange={(e) => setPendingPages(e.target.value)}
                placeholder="e.g. 120" autoFocus={detectFailed || detectedPages === null}
                onKeyDown={(e) => e.key === "Enter" && confirmUploadSave()}
                className="w-full border rounded-md px-3 py-2 mb-2 focus:outline-none focus:ring-2" style={{ borderColor: BORDER }} />
              {detectedPages !== null ? (
                <p className="text-xs mb-3 flex items-center gap-1" style={{ color: MUTED }}><Pencil size={11} /> Enter the correct page count below.</p>
              ) : detectFailed ? (
                <p className="text-xs mb-3" style={{ color: MUTED }}>We couldn't automatically detect the page count for this file — please enter it manually.</p>
              ) : (
                <p className="text-xs mb-3" style={{ color: MUTED }}>Used to calculate the reading-progress bar shown on the shelf and dashboard.</p>
              )}
            </>
          )}

          {uploadError && <p className="text-sm flex items-center gap-1.5 mb-2" style={{ color: RED }}><AlertCircle size={14} /> {uploadError}</p>}
          <div className="flex justify-end gap-3 mt-3">
            <button onClick={cancelUpload} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>Cancel</button>
            <button onClick={confirmUploadSave} disabled={!pendingName.trim() || saving || pageStage !== "entry" || !pendingPages}
              className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white disabled:opacity-40 flex items-center gap-2" style={{ background: LEATHER }}>
              {saving ? <Loader2 className="animate-spin" size={14} /> : <Check size={14} />} Save to shelf
            </button>
          </div>
        </Modal>
      )}

      {confirmDelete && (
        <Modal onClose={() => setConfirmDelete(null)}>
          <h3 className="font-serif text-xl font-bold mb-2" style={{ color: LEATHER_DARK }}>Delete {confirmDelete.type === "folder" ? "shelf" : "book"}?</h3>
          <p className="text-sm mb-6" style={{ color: MUTED }}>
            "{confirmDelete.name}" will be permanently removed{confirmDelete.type === "folder" ? ", along with every book on it" : ""}. This cannot be undone.
          </p>
          <div className="flex justify-end gap-3">
            <button onClick={() => setConfirmDelete(null)} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>Cancel</button>
            <button onClick={() => confirmDelete.type === "folder" ? deleteFolder(confirmDelete.id) : deleteBook(confirmDelete.folderId, confirmDelete.id)}
              className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white flex items-center gap-2" style={{ background: RED }}>
              <Trash2 size={14} /> Delete
            </button>
          </div>
        </Modal>
      )}

      {readingTarget && (
        <BookReader
          book={readingTarget.book}
          onClose={() => setReadingTarget(null)}
          onCommitProgress={(page) => updateBook(readingTarget.folderId, readingTarget.book.id, { last_read_page: page, last_read_at: new Date().toISOString() })}
          onSaveEdit={(html) => updateBook(readingTarget.folderId, readingTarget.book.id, { edited_html: html, edited_at: new Date().toISOString() })}
        />
      )}

      {toast && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 px-4 py-2.5 rounded-lg text-sm text-white shadow-lg flex items-center gap-2 z-50 pop" style={{ background: LEATHER_DARK }}>
          <Check size={14} style={{ color: GOLD }} /> {toast}
        </div>
      )}
    </div>
  );
}

/* ============================== TOP BAR ============================== */
function TopBar({ view, theme, mode, onToggleMode, onHome, onOpenSettings }) {
  return (
    <header style={{ background: LEATHER_DARK, borderBottom: `3px solid ${GOLD}` }}>
      <div className="max-w-6xl mx-auto px-6 py-5 flex items-center justify-between">
        <button onClick={onHome} className="flex items-center gap-3 min-w-0">
          {theme.logo_url ? (
            <img src={theme.logo_url} alt="" className="h-9 w-9 rounded-md object-cover shrink-0" />
          ) : (
            <div className="h-9 w-9 rounded-md flex items-center justify-center shrink-0" style={{ background: GOLD }}>
              <BookOpen size={19} style={{ color: LEATHER_DARK }} />
            </div>
          )}
          <div className="text-left min-w-0">
            <h1 className="font-serif text-2xl font-bold text-white leading-none truncate">{theme.site_name || "Readnexa"}</h1>
            <p className="text-[11px] tracking-widest uppercase font-mono truncate" style={{ color: "#D8C7A8" }}>{theme.tagline || "Read · Track · Remember"}</p>
          </div>
        </button>
        <div className="flex items-center gap-2 shrink-0">
          <button onClick={onHome} className="flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-md"
            style={{ color: "#F1E6D2", background: view === "dashboard" ? "rgba(255,255,255,0.08)" : "transparent", fontWeight: view === "dashboard" ? 600 : 400 }}>
            <LayoutDashboard size={15} /> <span className="hidden sm:inline">Dashboard</span>
          </button>
          <button onClick={onToggleMode} title={mode === "dark" ? "Switch to light mode" : "Switch to dark mode"} className="p-2 rounded-md hover:bg-white/10" style={{ color: "#F1E6D2" }}>
            {mode === "dark" ? <Sun size={17} /> : <Moon size={17} />}
          </button>
          <button onClick={onOpenSettings} title="Site settings" className="p-2 rounded-md hover:bg-white/10" style={{ color: "#F1E6D2" }}>
            <SettingsIcon size={17} />
          </button>
        </div>
      </div>
    </header>
  );
}

/* ============================== SETTINGS MODAL ============================== */
function SettingsModal({ theme, onClose, onSave }) {
  const [siteName, setSiteName] = useState(theme.site_name || "Readnexa");
  const [tagline, setTagline] = useState(theme.tagline || "");
  const [primary, setPrimary] = useState(theme.primary_color || DEFAULT_PRIMARY);
  const [accent, setAccent] = useState(theme.accent_color || DEFAULT_ACCENT);
  const [logoFile, setLogoFile] = useState(null);
  const [logoPreview, setLogoPreview] = useState(theme.logo_url || null);
  const [removeLogo, setRemoveLogo] = useState(false);
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState("");
  const logoInputRef = useRef(null);

  const onPickLogo = (e) => {
    const file = e.target.files && e.target.files[0];
    e.target.value = "";
    if (!file) return;
    if (!file.type.startsWith("image/")) { setErr("Please choose an image file for the logo."); return; }
    if (file.size > 1.5 * 1024 * 1024) { setErr("Logo image should be under 1.5MB."); return; }
    setErr("");
    setLogoFile(file);
    setRemoveLogo(false);
    setLogoPreview(URL.createObjectURL(file));
  };

  const handleSave = async () => {
    if (!siteName.trim()) { setErr("Site name can't be empty."); return; }
    setSaving(true);
    let logo_url = theme.logo_url || null;
    try {
      if (removeLogo) {
        logo_url = null;
      } else if (logoFile) {
        const path = `logo-${Date.now()}-${logoFile.name}`;
        const { error: upErr } = await supabase.storage.from(ASSETS_BUCKET).upload(path, logoFile, { upsert: false });
        if (upErr) throw upErr;
        const { data: pub } = supabase.storage.from(ASSETS_BUCKET).getPublicUrl(path);
        logo_url = pub.publicUrl;
      }
      await onSave({ site_name: siteName.trim(), tagline: tagline.trim(), primary_color: primary, accent_color: accent, logo_url });
      onClose();
    } catch (e) {
      setErr("Could not save logo: " + (e.message || "unknown error") + ". Make sure the 'assets' storage bucket exists and is public.");
    }
    setSaving(false);
  };

  return (
    <Modal onClose={onClose}>
      <h3 className="font-serif text-xl font-bold mb-4" style={{ color: LEATHER_DARK }}>Site settings</h3>

      <label className="text-sm block mb-1" style={{ color: MUTED }}>Site name</label>
      <input value={siteName} onChange={(e) => setSiteName(e.target.value)}
        className="w-full border rounded-md px-3 py-2 mb-4 focus:outline-none focus:ring-2" style={{ borderColor: BORDER }} />

      <label className="text-sm block mb-1" style={{ color: MUTED }}>Tagline</label>
      <input value={tagline} onChange={(e) => setTagline(e.target.value)} placeholder="Read · Track · Remember"
        className="w-full border rounded-md px-3 py-2 mb-4 focus:outline-none focus:ring-2" style={{ borderColor: BORDER }} />

      <label className="text-sm block mb-2" style={{ color: MUTED }}>Logo</label>
      <div className="flex items-center gap-3 mb-4">
        <div className="h-12 w-12 rounded-md flex items-center justify-center shrink-0 overflow-hidden" style={{ background: primary }}>
          {logoPreview && !removeLogo ? <img src={logoPreview} className="h-full w-full object-cover" alt="" /> : <BookOpen size={20} color="white" />}
        </div>
        <button onClick={() => logoInputRef.current.click()} className="px-3 py-1.5 rounded-md text-sm" style={{ border: `1px solid ${BORDER}`, color: LEATHER_DARK }}>Upload image</button>
        {logoPreview && !removeLogo && (
          <button onClick={() => { setRemoveLogo(true); setLogoPreview(null); setLogoFile(null); }} className="text-sm" style={{ color: RED }}>Remove</button>
        )}
        <input ref={logoInputRef} type="file" accept="image/*" className="hidden" onChange={onPickLogo} />
      </div>

      <div className="grid grid-cols-2 gap-4 mb-4">
        <div>
          <label className="text-sm block mb-1" style={{ color: MUTED }}>Primary color</label>
          <div className="flex items-center gap-2">
            <input type="color" value={primary} onChange={(e) => setPrimary(e.target.value)} className="h-9 w-10 rounded border p-0.5" style={{ borderColor: BORDER }} />
            <input value={primary} onChange={(e) => setPrimary(e.target.value)} className="w-full border rounded-md px-2 py-1.5 text-sm font-mono" style={{ borderColor: BORDER }} />
          </div>
        </div>
        <div>
          <label className="text-sm block mb-1" style={{ color: MUTED }}>Accent color</label>
          <div className="flex items-center gap-2">
            <input type="color" value={accent} onChange={(e) => setAccent(e.target.value)} className="h-9 w-10 rounded border p-0.5" style={{ borderColor: BORDER }} />
            <input value={accent} onChange={(e) => setAccent(e.target.value)} className="w-full border rounded-md px-2 py-1.5 text-sm font-mono" style={{ borderColor: BORDER }} />
          </div>
        </div>
      </div>

      {err && <p className="text-sm flex items-center gap-1.5 mb-3" style={{ color: RED }}><AlertCircle size={14} /> {err}</p>}

      <div className="flex justify-end gap-3 mt-2">
        <button onClick={onClose} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>Cancel</button>
        <button onClick={handleSave} disabled={saving} className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white flex items-center gap-2 disabled:opacity-50" style={{ background: primary }}>
          {saving ? <Loader2 className="animate-spin" size={14} /> : <Check size={14} />} Save settings
        </button>
      </div>
    </Modal>
  );
}

/* ============================== MODAL ============================== */
function Modal({ children, onClose }) {
  return (
    <div className="fixed inset-0 bg-black/45 flex items-center justify-center z-50 px-4 fade" onClick={onClose}>
      <div className="rounded-xl shadow-2xl w-full max-w-md p-6 pop" style={{ background: CARD }} onClick={(e) => e.stopPropagation()}>
        {children}
      </div>
    </div>
  );
}

/* ============================== CIRCLE PROGRESS ============================== */
function CircleProgress({ percent, size = 54, stroke = 6, color = GREEN }) {
  const r = (size - stroke) / 2;
  const c = 2 * Math.PI * r;
  const off = c - (percent / 100) * c;
  return (
    <svg width={size} height={size} className="shrink-0">
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke={BORDER} strokeWidth={stroke} />
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke={color} strokeWidth={stroke}
        strokeDasharray={c} strokeDashoffset={off} strokeLinecap="round"
        transform={`rotate(-90 ${size / 2} ${size / 2})`} style={{ transition: "stroke-dashoffset .8s ease" }} />
      <text x="50%" y="50%" textAnchor="middle" dy="0.35em" fontSize={size * 0.26} fontWeight="700" fill={INK}>{percent}%</text>
    </svg>
  );
}

/* ============================== DASHBOARD ============================== */
function Dashboard({ folders, booksByFolder, allBooksFlat, onOpenFolder, onNewFolder, onEditFolder, onDeleteFolder, onContinueReading }) {
  const totalBooks = allBooksFlat.length;
  const totalPagesAll = allBooksFlat.reduce((s, b) => s + (b.total_pages || 0), 0);
  const readPagesAll = allBooksFlat.reduce((s, b) => s + Math.min(b.last_read_page || 0, b.total_pages || 0), 0);
  const overallPct = totalPagesAll > 0 ? Math.round((readPagesAll / totalPagesAll) * 100) : 0;
  const reading = allBooksFlat.filter((b) => { const p = progressOf(b); return p > 0 && p < 100; }).length;
  const finished = allBooksFlat.filter((b) => progressOf(b) >= 100).length;

  const chartData = folders.map((f) => {
    const list = booksByFolder[f.id] || [];
    const tp = list.reduce((s, b) => s + (b.total_pages || 0), 0);
    const rp = list.reduce((s, b) => s + Math.min(b.last_read_page || 0, b.total_pages || 0), 0);
    return { name: f.name, percent: tp > 0 ? Math.round((rp / tp) * 100) : 0, count: list.length };
  });

  const continueReading = allBooksFlat
    .filter((b) => { const p = progressOf(b); return p > 0 && p < 100; })
    .sort((a, b) => new Date(b.last_read_at || 0) - new Date(a.last_read_at || 0))
    .slice(0, 4);

  return (
    <div>
      <div className="mb-8 rise">
        <p className="text-xs uppercase tracking-widest font-mono" style={{ color: GOLD }}>Your library at a glance</p>
        <h2 className="font-serif text-3xl font-bold" style={{ color: LEATHER_DARK }}>Dashboard</h2>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
        <StatCard icon={<BookCopy size={18} />} label="Total books" value={totalBooks} delay={0} />
        <StatCard icon={<Library size={18} />} label="Shelves" value={folders.length} delay={60} />
        <StatCard icon={<Clock size={18} />} label="Currently reading" value={reading} delay={120} />
        <StatCard icon={<CheckCircle2 size={18} />} label="Finished" value={finished} delay={180} />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6 mb-10">
        <div className="lg:col-span-2 rounded-xl p-6 rise" style={{ background: CARD, border: `1px solid ${BORDER}`, animationDelay: "80ms" }}>
          <p className="text-sm mb-1" style={{ color: MUTED }}>Overall completion</p>
          <div className="flex items-center gap-5 mt-3">
            <CircleProgress percent={overallPct} size={92} stroke={9} color={GREEN} />
            <div>
              <p className="font-serif text-2xl font-bold" style={{ color: LEATHER_DARK }}>{readPagesAll.toLocaleString()} <span className="text-base font-sans font-normal" style={{ color: MUTED }}>/ {totalPagesAll.toLocaleString()} pages</span></p>
              <p className="text-sm mt-1" style={{ color: MUTED }}>across every shelf</p>
            </div>
          </div>
        </div>

        <div className="lg:col-span-3 rounded-xl p-6 rise" style={{ background: CARD, border: `1px solid ${BORDER}`, animationDelay: "140ms" }}>
          <p className="text-sm mb-3" style={{ color: MUTED }}>Completion by shelf</p>
          {chartData.length === 0 ? (
            <p className="text-sm py-8 text-center" style={{ color: MUTED }}>No shelves yet.</p>
          ) : (
            <ResponsiveContainer width="100%" height={Math.max(120, chartData.length * 44)}>
              <BarChart data={chartData} layout="vertical" margin={{ left: 4, right: 24 }}>
                <XAxis type="number" domain={[0, 100]} hide />
                <YAxis dataKey="name" type="category" width={130} tick={{ fontSize: 12, fill: INK }} axisLine={false} tickLine={false} />
                <Tooltip formatter={(v) => [`${v}%`, "Complete"]} contentStyle={{ borderRadius: 8, borderColor: BORDER }} />
                <Bar dataKey="percent" radius={[0, 6, 6, 0]} barSize={16}>
                  {chartData.map((d, i) => <Cell key={i} fill={spineColor(folders[i]?.id || String(i))} />)}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          )}
        </div>
      </div>

      {continueReading.length > 0 && (
        <div className="mb-10">
          <h3 className="font-serif text-lg font-bold mb-4" style={{ color: LEATHER_DARK }}>Continue reading</h3>
          <div className="flex gap-4 overflow-x-auto pb-2">
            {continueReading.map((b, i) => {
              const pct = progressOf(b);
              return (
                <button key={b.id} onClick={() => onContinueReading(b)}
                  className="book-card text-left shrink-0 w-52 rounded-lg overflow-hidden rise" style={{ background: CARD, border: `1px solid ${BORDER}`, animationDelay: `${i * 70}ms` }}>
                  <div className="h-3" style={{ background: spineColor(b.folder_id) }} />
                  <div className="p-4">
                    <p className="text-xs font-mono mb-1" style={{ color: MUTED }}>{b.folderName}</p>
                    <p className="font-serif font-bold text-sm mb-3" style={{ color: LEATHER_DARK }}>{b.name}</p>
                    <div className="h-1.5 rounded-full overflow-hidden mb-1" style={{ background: BORDER }}>
                      <div className="h-full progress-fill rounded-full" style={{ width: `${pct}%`, background: GOLD }} />
                    </div>
                    <p className="text-xs" style={{ color: MUTED }}>{pct}% · page {b.last_read_page} of {b.total_pages}</p>
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      )}

      <div className="flex items-end justify-between mb-5">
        <h3 className="font-serif text-lg font-bold" style={{ color: LEATHER_DARK }}>Your shelves</h3>
        <button onClick={onNewFolder} className="btn-lift flex items-center gap-1.5 px-4 py-2 rounded-md text-sm font-medium text-white" style={{ background: LEATHER }}>
          <Plus size={16} /> New shelf
        </button>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-5">
        {folders.map((f, i) => {
          const list = booksByFolder[f.id] || [];
          const tp = list.reduce((s, b) => s + (b.total_pages || 0), 0);
          const rp = list.reduce((s, b) => s + Math.min(b.last_read_page || 0, b.total_pages || 0), 0);
          const pct = tp > 0 ? Math.round((rp / tp) * 100) : 0;
          return (
            <ShelfCard key={f.id} folder={f} count={list.length} percent={pct} delay={i * 70}
              onOpen={() => onOpenFolder(f.id)} onEdit={() => onEditFolder(f)} onDelete={() => onDeleteFolder(f)} />
          );
        })}
      </div>
    </div>
  );
}

function StatCard({ icon, label, value, delay }) {
  return (
    <div className="rounded-xl p-5 rise" style={{ background: CARD, border: `1px solid ${BORDER}`, animationDelay: `${delay}ms` }}>
      <div className="flex items-center gap-2 mb-2" style={{ color: GOLD }}>{icon}<span className="text-xs uppercase tracking-wide font-mono" style={{ color: MUTED }}>{label}</span></div>
      <p className="font-serif text-3xl font-bold" style={{ color: LEATHER_DARK }}>{value}</p>
    </div>
  );
}

function ShelfCard({ folder, count, percent, delay, onOpen, onEdit, onDelete }) {
  const color = spineColor(folder.id);
  const [hover, setHover] = useState(false);
  return (
    <div className="shelf-card rise cursor-pointer" style={{ animationDelay: `${delay}ms` }}
      onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)} onClick={onOpen}>
      <div className="rounded-xl overflow-hidden" style={{ background: CARD, border: `1px solid ${BORDER}` }}>
        <div className="h-2.5" style={{ background: color }} />
        <div className="p-5 flex items-start gap-4">
          <CircleProgress percent={percent} size={54} stroke={6} color={color} />
          <div className="flex-1 min-w-0">
            <div className="flex items-start justify-between gap-2">
              <h4 className="font-serif font-bold text-base truncate" style={{ color: LEATHER_DARK }}>{folder.name}</h4>
              {hover && (
                <div className="flex items-center gap-1 shrink-0">
                  <button onClick={(e) => { e.stopPropagation(); onEdit(); }} className="p-1 -m-1" style={{ color: MUTED }} title="Rename shelf">
                    <Pencil size={13} />
                  </button>
                  <button onClick={(e) => { e.stopPropagation(); onDelete(); }} className="p-1 -m-1" style={{ color: MUTED }} title="Delete shelf">
                    <Trash2 size={14} />
                  </button>
                </div>
              )}
            </div>
            <p className="text-xs font-mono mt-1" style={{ color: MUTED }}>{count} book{count !== 1 ? "s" : ""}</p>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ============================== SHELF VIEW ============================== */
function ShelfView({ folder, books, onBack, onUploadClick, onRead, onEditBook, onResetProgress, onDeleteBook }) {
  if (!folder) return null;
  const color = spineColor(folder.id);
  return (
    <div className="fade">
      <button onClick={onBack} className="flex items-center gap-1.5 text-sm mb-5" style={{ color: MUTED }}><ArrowLeft size={15} /> Dashboard</button>
      <div className="flex items-end justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="h-11 w-11 rounded-lg flex items-center justify-center" style={{ background: color }}>
            <Library size={20} color="white" />
          </div>
          <div>
            <h2 className="font-serif text-2xl font-bold" style={{ color: LEATHER_DARK }}>{folder.name}</h2>
            <p className="text-sm" style={{ color: MUTED }}>{books.length} book{books.length !== 1 ? "s" : ""} on this shelf</p>
          </div>
        </div>
        <button onClick={onUploadClick} className="btn-lift flex items-center gap-1.5 px-4 py-2 rounded-md text-sm font-medium text-white shrink-0" style={{ background: LEATHER }}>
          <Upload size={16} /> Upload Book / Document
        </button>
      </div>

      {books.length === 0 ? (
        <div className="text-center py-16 border-2 border-dashed rounded-lg" style={{ borderColor: BORDER }}>
          <BookMarked size={30} className="mx-auto mb-3" style={{ color: BORDER }} />
          <p className="mb-4" style={{ color: MUTED }}>This shelf is empty.</p>
          <button onClick={onUploadClick} className="text-sm font-medium underline" style={{ color: LEATHER }}>Upload the first PDF or Word document</button>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4">
          {books.map((b, i) => <BookRow key={b.id} book={b} color={color} delay={i * 50} onRead={() => onRead(b)} onEdit={() => onEditBook(b)} onReset={() => onResetProgress(b)} onDelete={() => onDeleteBook(b)} />)}
        </div>
      )}
    </div>
  );
}

function BookRow({ book, color, delay, onRead, onEdit, onReset, onDelete }) {
  const pct = progressOf(book);
  const status = statusOf(book);
  const stamp = fmtStamp(book.uploaded_at);
  return (
    <div className="rise rounded-xl p-5 flex flex-col sm:flex-row sm:items-center gap-4" style={{ background: CARD, border: `1px solid ${BORDER}`, animationDelay: `${delay}ms` }}>
      <div className="h-14 w-11 rounded-sm shrink-0 flex items-center justify-center" style={{ background: color }}>
        <FileText size={18} color="white" />
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <p className="font-serif font-bold" style={{ color: LEATHER_DARK }}>{book.name}</p>
          <span className="text-xs px-2 py-0.5 rounded-full font-medium" style={{ background: `color-mix(in srgb, ${status.color} 22%, transparent)`, color: status.color }}>{status.label}</span>
        </div>
        <p className="text-xs font-mono mt-0.5" style={{ color: MUTED }}>{book.file_name} · {fmtBytes(book.size)} · added {stamp.date}</p>
        <div className="flex items-center gap-3 mt-2.5">
          <div className="h-2 rounded-full overflow-hidden flex-1 max-w-xs" style={{ background: BORDER }}>
            <div className="h-full progress-fill rounded-full" style={{ width: `${pct}%`, background: pct >= 100 ? GREEN : GOLD }} />
          </div>
          <span className="text-xs font-mono w-28 shrink-0" style={{ color: MUTED }}>{pct}% · pg {book.last_read_page}/{book.total_pages}</span>
        </div>
      </div>
      <div className="flex items-center gap-1.5 shrink-0 self-end sm:self-center">
        <button onClick={onRead} className="btn-lift flex items-center gap-1.5 px-3 py-2 rounded-md text-sm font-medium text-white" style={{ background: color }}>
          <BookOpen size={15} /> Read
        </button>
        <button onClick={onEdit} title="Edit details" className="p-2 rounded-md hover:bg-black/5" style={{ color: MUTED }}><Pencil size={16} /></button>
        {pct > 0 && (
          <button onClick={onReset} title="Reset reading progress to 0%" className="p-2 rounded-md hover:bg-black/5" style={{ color: MUTED }}><RotateCcw size={16} /></button>
        )}
        <a href={book.file_url} download={book.file_name} title="Download" className="p-2 rounded-md hover:bg-black/5" style={{ color: MUTED }}><Download size={17} /></a>
        <button onClick={onDelete} title="Delete" className="p-2 rounded-md hover:bg-black/5" style={{ color: MUTED }}><Trash2 size={17} /></button>
      </div>
    </div>
  );
}

/* ============================== BOOK READER ============================== */
function BookReader({ book, onClose, onCommitProgress, onSaveEdit }) {
  const isPdf = book.file_type === "pdf";
  const isDocx = book.file_type === "docx";
  const isLegacyDoc = book.file_type === "doc";

  const [pdfPage, setPdfPage] = useState(book.last_read_page || 1);

  const [pages, setPages] = useState(null); // array of html strings, one per virtual page
  const [pageIndex, setPageIndex] = useState(Math.max(0, Math.min((book.total_pages || 1) - 1, (book.last_read_page || 1) - 1)));
  const [htmlError, setHtmlError] = useState("");
  const [editMode, setEditMode] = useState(false);
  const [isDirty, setIsDirty] = useState(false);
  const [fontScale, setFontScale] = useState(1);
  const contentRef = useRef(null);

  const [stage, setStage] = useState("reading");
  const [manualPage, setManualPage] = useState("");

  useEffect(() => {
    if (isDocx) {
      (async () => {
        try {
          let chunks;
          if (book.edited_html) {
            let parsedPages = null;
            try {
              const maybe = JSON.parse(book.edited_html);
              if (Array.isArray(maybe) && maybe.length) parsedPages = maybe;
            } catch (e) { /* not JSON — legacy plain-html save */ }
            chunks = parsedPages || chunkHtmlForReading(book.edited_html);
          } else {
            const res = await fetch(book.file_url);
            const buf = await res.arrayBuffer();
            const result = await mammoth.convertToHtml({ arrayBuffer: buf });
            const html = result.value || "<p><em>(Empty document)</em></p>";
            chunks = chunkHtmlForReading(html);
          }
          setPages(chunks);
          // Resume at the chunk that proportionally matches previously saved progress.
          const total = book.total_pages || 1;
          const startBookPage = book.last_read_page || 1;
          const startIdx = Math.max(0, Math.min(chunks.length - 1, Math.round((startBookPage / total) * chunks.length) - 1));
          setPageIndex(startIdx);
        } catch (e) {
          setHtmlError("This document could not be previewed. You can still download it.");
        }
      })();
    }
  }, [isDocx, book.file_url, book.edited_html, book.total_pages, book.last_read_page]);

  useEffect(() => {
    if (isDocx && pages && contentRef.current) {
      contentRef.current.innerHTML = pages[pageIndex] || "";
    }
  }, [isDocx, pages, pageIndex]);

  // Maps an internal content-chunk index to the "book page" number the user
  // actually declared, so the counter and progress % always match their total.
  const bookPageForIndex = (idx) => {
    if (!pages || pages.length === 0) return 1;
    return Math.max(1, Math.min(book.total_pages, Math.round(((idx + 1) / pages.length) * book.total_pages)));
  };
  const indexForBookPage = (bp) => {
    if (!pages || pages.length === 0) return 0;
    const idx = Math.round((bp / book.total_pages) * pages.length) - 1;
    return Math.max(0, Math.min(pages.length - 1, idx));
  };

  const handleInput = () => { if (!isDirty) setIsDirty(true); };

  const enterEdit = () => setEditMode(true);
  const saveEdit = () => {
    const newHtml = contentRef.current ? contentRef.current.innerHTML : pages[pageIndex];
    const nextPages = pages.map((p, i) => (i === pageIndex ? newHtml : p));
    setPages(nextPages);
    onSaveEdit(JSON.stringify(nextPages));
    setIsDirty(false);
    setEditMode(false);
  };
  const discardEdit = () => {
    if (contentRef.current) contentRef.current.innerHTML = pages[pageIndex];
    setIsDirty(false);
    setEditMode(false);
  };

  const goPrev = () => { if (!editMode) setPageIndex((p) => Math.max(0, p - 1)); };
  const goNext = () => { if (!editMode && pages) setPageIndex((p) => Math.min(pages.length - 1, p + 1)); };

  const currentPage = isPdf ? pdfPage : bookPageForIndex(pageIndex);
  const requestClose = () => {
    if (isDocx && editMode && isDirty) { setStage("discardCheck"); return; }
    setStage("confirmPage");
  };
  const finalizeClose = (page) => { onCommitProgress(page); onClose(); };

  return (
    <div className="fixed inset-0 z-50 flex flex-col fade" style={{ background: "rgba(20,18,16,0.96)" }}>
      <div className="flex items-center justify-between px-5 py-3 shrink-0" style={{ background: LEATHER_DARK, borderBottom: `2px solid ${GOLD}` }}>
        <div className="min-w-0">
          <p className="font-serif font-bold text-white truncate">{book.name}</p>
          <p className="text-xs font-mono" style={{ color: "#D8C7A8" }}>{book.file_name}</p>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          {isDocx && !isLegacyDoc && !editMode && (
            <>
              <button onClick={() => setFontScale((s) => Math.max(0.8, +(s - 0.1).toFixed(2)))} title="Decrease text size" className="p-2 rounded-md hover:bg-white/10 text-white"><ZoomOut size={16} /></button>
              <button onClick={() => setFontScale((s) => Math.min(1.5, +(s + 0.1).toFixed(2)))} title="Increase text size" className="p-2 rounded-md hover:bg-white/10 text-white"><ZoomIn size={16} /></button>
              <button onClick={enterEdit} className="btn-lift flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium" style={{ background: GOLD, color: LEATHER_DARK }}>
                <Pencil size={14} /> Edit
              </button>
            </>
          )}
          {isDocx && editMode && (
            <>
              <button onClick={discardEdit} className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm" style={{ color: "#F1E6D2" }}><RotateCcw size={14} /> Discard</button>
              <button onClick={saveEdit} disabled={!isDirty} className="btn-lift flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium disabled:opacity-40" style={{ background: GREEN, color: "white" }}>
                <Save size={14} /> Save changes
              </button>
            </>
          )}
          <button onClick={requestClose} className="p-2 rounded-md hover:bg-white/10 text-white"><X size={20} /></button>
        </div>
      </div>

      {editMode && (
        <div className="text-center text-xs py-1.5" style={{ background: "#2F241D", color: GOLD }}>
          Editing enabled — edited text appears in <span style={{ color: GREEN, fontWeight: 700 }}>green</span> until you save. Page navigation is paused while editing.
        </div>
      )}

      <div className="flex-1 overflow-hidden flex flex-col items-center px-4 py-4">
        {isPdf && (
          <div className="w-full h-full max-w-4xl flex flex-col">
            <div className="flex-1 rounded-lg overflow-hidden shadow-2xl" style={{ background: "white" }}>
              <embed src={book.file_url} type="application/pdf" className="w-full h-full" />
            </div>
            <div className="flex items-center justify-center gap-4 py-3">
              <button onClick={() => setPdfPage((p) => Math.max(1, p - 1))} className="p-2 rounded-md text-white hover:bg-white/10"><ChevronLeft size={18} /></button>
              <div className="flex items-center gap-2 text-sm" style={{ color: "#F1E6D2" }}>
                Page
                <input type="number" value={pdfPage} min={1} max={book.total_pages}
                  onChange={(e) => setPdfPage(Math.min(book.total_pages, Math.max(1, parseInt(e.target.value, 10) || 1)))}
                  className="w-16 text-center rounded-md px-2 py-1 text-black" />
                of {book.total_pages}
              </div>
              <button onClick={() => setPdfPage((p) => Math.min(book.total_pages, p + 1))} className="p-2 rounded-md text-white hover:bg-white/10"><ChevronRight size={18} /></button>
            </div>
            <p className="text-center text-xs pb-1" style={{ color: "#B7A88C" }}>Use the page controls above to bookmark where you are as you read.</p>
          </div>
        )}

        {isDocx && (
          <div className="w-full h-full max-w-5xl flex flex-col">
            {htmlError ? (
              <div className="flex-1 flex items-center justify-center text-center px-6" style={{ color: "#F1E6D2" }}>
                <div><AlertCircle className="mx-auto mb-3" /><p>{htmlError}</p></div>
              </div>
            ) : pages === null ? (
              <div className="flex-1 flex items-center justify-center gap-2" style={{ color: "white" }}><Loader2 className="animate-spin" /> Preparing document…</div>
            ) : (
              <div className="flex-1 overflow-y-auto flex items-start justify-center py-2" style={{ background: "#3A3630", borderRadius: 10 }}>
                <div key={pageIndex} className="fade" style={{
                  background: "white", width: "100%", maxWidth: 860, minHeight: "100%",
                  boxShadow: "0 12px 34px rgba(0,0,0,0.4)", padding: "72px 88px 48px",
                  display: "flex", flexDirection: "column",
                }}>
                  <div
                    ref={contentRef}
                    data-editable="true"
                    contentEditable={editMode}
                    suppressContentEditableWarning
                    onInput={handleInput}
                    className={isDirty ? "editing-live" : ""}
                    style={{ outline: "none", lineHeight: 1.75, color: "#241A15", fontFamily: "Georgia, serif", fontSize: `${18 * fontScale}px`, flex: 1 }}
                  />
                  <p className="text-center text-xs pt-8" style={{ color: "#B0A99C", fontFamily: "Georgia, serif" }}>Page {bookPageForIndex(pageIndex)}</p>
                </div>
              </div>
            )}
            <div className="flex items-center justify-center gap-4 py-3">
              <button onClick={goPrev} disabled={editMode || pageIndex === 0} className="p-2 rounded-md text-white hover:bg-white/10 disabled:opacity-30"><ChevronLeft size={18} /></button>
              <div className="flex items-center gap-2 text-sm" style={{ color: "#F1E6D2" }}>
                Page
                <input type="number" value={bookPageForIndex(pageIndex)} min={1} max={book.total_pages} disabled={editMode}
                  onChange={(e) => setPageIndex(indexForBookPage(Math.min(book.total_pages, Math.max(1, parseInt(e.target.value, 10) || 1))))}
                  className="w-16 text-center rounded-md px-2 py-1 text-black disabled:opacity-60" />
                of {book.total_pages}
              </div>
              <button onClick={goNext} disabled={editMode || !pages || pageIndex >= pages.length - 1} className="p-2 rounded-md text-white hover:bg-white/10 disabled:opacity-30"><ChevronRight size={18} /></button>
            </div>
          </div>
        )}

        {isLegacyDoc && (
          <div className="flex-1 flex items-center justify-center text-center px-6" style={{ color: "#F1E6D2" }}>
            <div>
              <FileText className="mx-auto mb-3" size={28} />
              <p className="mb-3">Legacy .doc files can't be previewed in-browser.</p>
              <a href={book.file_url} download={book.file_name} className="underline text-sm">Download to view</a>
            </div>
          </div>
        )}
      </div>

      {stage === "discardCheck" && (
        <Modal onClose={() => setStage("reading")}>
          <h3 className="font-serif text-xl font-bold mb-2" style={{ color: LEATHER_DARK }}>Unsaved edits</h3>
          <p className="text-sm mb-6" style={{ color: MUTED }}>You have edits that haven't been saved yet. What would you like to do?</p>
          <div className="flex justify-end gap-3 flex-wrap">
            <button onClick={() => setStage("reading")} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>Keep editing</button>
            <button onClick={() => { discardEdit(); setStage("confirmPage"); }} className="px-4 py-2 rounded-md text-sm font-medium" style={{ color: RED }}>Discard edits</button>
            <button onClick={() => { saveEdit(); setStage("confirmPage"); }} className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white" style={{ background: GREEN }}>Save & continue</button>
          </div>
        </Modal>
      )}

      {stage === "confirmPage" && (
        <Modal onClose={() => finalizeClose(currentPage)}>
          <h3 className="font-serif text-xl font-bold mb-2" style={{ color: LEATHER_DARK }}>Save your reading progress?</h3>
          <p className="text-sm mb-6" style={{ color: MUTED }}>
            You've read up to page <span className="font-semibold" style={{ color: LEATHER_DARK }}>{currentPage}</span> of <span className="font-semibold" style={{ color: LEATHER_DARK }}>{book.total_pages}</span>. Confirm?
          </p>
          <div className="flex justify-end gap-3">
            <button onClick={() => { setManualPage(String(currentPage)); setStage("manualPage"); }} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>No, let me correct it</button>
            <button onClick={() => finalizeClose(currentPage)} className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white flex items-center gap-2" style={{ background: GREEN }}><Check size={14} /> Yes, save</button>
          </div>
        </Modal>
      )}

      {stage === "manualPage" && (
        <Modal onClose={() => finalizeClose(currentPage)}>
          <h3 className="font-serif text-xl font-bold mb-3" style={{ color: LEATHER_DARK }}>Enter the page you reached</h3>
          <input type="number" min={0} max={book.total_pages} autoFocus value={manualPage} onChange={(e) => setManualPage(e.target.value)}
            className="w-full border rounded-md px-3 py-2 mb-4 focus:outline-none focus:ring-2" style={{ borderColor: BORDER }} />
          <div className="flex justify-end gap-3">
            <button onClick={() => setStage("confirmPage")} className="px-4 py-2 rounded-md text-sm" style={{ color: MUTED }}>Back</button>
            <button onClick={() => finalizeClose(Math.min(book.total_pages, Math.max(0, parseInt(manualPage, 10) || 0)))}
              className="btn-lift px-4 py-2 rounded-md text-sm font-medium text-white flex items-center gap-2" style={{ background: GREEN }}><Check size={14} /> Save progress</button>
          </div>
        </Modal>
      )}
    </div>
  );
}
